### ISSUE TITLE
Проблемы с AJAX после перевода - исправьте!

### ISSUE THREAD

**Issue by maiskiykot** [likhobory/SuiteCRM7RU#4]
Я попробовал несколько версий suiteCRM и как только ставлю русификатор - сразу слетают все разделы админки - перестают открываться - пишет что не поддерживается AJAX. Удаляешь русификатор - все снова работает. Дайте фикс плиз! Открываю в IE 11 windows 10 последняя. Спасибо!

**Comment by likhobory** [comment]
Подобные вопросы здесь не обсуждаются. Пожалуйста, создайте аналогичную тему на [форуме](https://community.suitecrm.com/t/github-ajax/61313), с указанием конкретной версии системы (желательно одну из последних из веток 7.8 или 7.10), версий браузеров (желательно не только IE 11), версии  языкового пакета.

**Comment by maiskiykot** [comment]
А чего тут обсуждать-то? Есть косяк - помогите исправить!

**Comment by horus68** [comment]
@maiskiykot We don't know how to reproduce your issue so we can't help you unless we have more details. There are different language packs and different SuiteCRm versions.
As told, please use the SuiteCRM forum for help, github is not for this kind of issues.
1- Please go to russian forum https://suitecrm.com/suitecrm/forum/suitecrm-forum-russian-language
(or the english one here:  https://suitecrm.com/suitecrm/forum/languages )
2- State your details:
= SuiteCRM versions
= Language pack version

Update: I see your post https://suitecrm.com/suitecrm/forum/suitecrm-forum-russian-general-discussion/20024-github-ajax

Note: likhobory will try to help you in russian or english in the forum, but i don't speak russian!
