### ISSUE TITLE
modules/Home/language/ru_ru.lang.php в 248 строке, в конце не хватает запятой.

### ISSUE THREAD

**Issue by DiVAN1x** [likhobory/SuiteCRM7RU#5]
modules/Home/language/ru_ru.lang.php 
в 248 строке, в конце не хватает запятой.

**Comment by likhobory** [comment]
Спасибо, [исправлено](https://github.com/likhobory/SuiteCRM7RU/commit/175c38fe4dcfc344bdc6810e03fcc347f8b97013).
